highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Junaid Lodhi's Resume
name: Muhammad Junaid Lodhi
email: junaidlodhi7@gmail.com
email_full: mailto:junaidlodhi7@gmail.com
website: github.io/mjunaidlodhi
website_full: https://biomadeira.github.io/
github: trending
twitter: twitter
tel: +92 3007 377077
tel_full: tel:+923327377077
city: Lahore
country: Pakistan


# needed for travis-ci build
exclude: [vendor]
